apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: shopfast
spec:
  type: ClusterIP # Only accessible within the cluster
  selector:
    app: auth-service
  ports:
  - port: 80
    targetPort: 5050