apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-catalog
  namespace: shopfast
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-catalog
  template:
    metadata:
      labels:
        app: product-catalog
    spec:
      containers:
      - name: catalog
        image: gcr.io/google-samples/microservices-demo/productcatalogservice:v0.8.0
        ports: 
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

  
