apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopfast
spec:
  replicas: 2
  selector:
    matchLabels:
      name: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web-ui
        image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "product-catalog:80"
        - name: CHECKOUT_SERVICE_ADDR
          value: "auth-service:80"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendation:80"
        - name: CURRENCY_SERVICE_ADDR
          value: "product-catalog:80"  # Just using as a placeholder
        ports:
        - continerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
