# auth-service-deployment.yaml (updated checkout service)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: shopfast
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth
        image: gcr.io/google-samples/microservices-demo/checkoutservice:v0.8.0
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        # Required services
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "product-catalog:80"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:80"  # We need to create this
        - name: PAYMENT_SERVICE_ADDR
          value: "payment-service:80"   # We need to create this
        - name: EMAIL_SERVICE_ADDR
          value: "email-service:80"     # We need to create this
        - name: CART_SERVICE_ADDR
          value: "cart-service:80"      # We need to create this
        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:80"  # We need to create this
        # Disable tracing/monitoring features
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# shipping-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: shopfast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
      - name: shipping
        image: gcr.io/google-samples/microservices-demo/shippingservice:v0.8.0
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# shipping-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  namespace: shopfast
spec:
  type: ClusterIP
  selector:
    app: shipping-service
  ports:
  - port: 80
    targetPort: 50051
---
# payment-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: shopfast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment
        image: gcr.io/google-samples/microservices-demo/paymentservice:v0.8.0
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# payment-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: shopfast
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
  - port: 80
    targetPort: 50051
---
# email-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
  namespace: shopfast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-service
  template:
    metadata:
      labels:
        app: email-service
    spec:
      containers:
      - name: email
        image: gcr.io/google-samples/microservices-demo/emailservice:v0.8.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# email-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: email-service
  namespace: shopfast
spec:
  type: ClusterIP
  selector:
    app: email-service
  ports:
  - port: 80
    targetPort: 8080
---
# cart-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  namespace: shopfast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart
        image: gcr.io/google-samples/microservices-demo/cartservice:v0.8.0
        ports:
        - containerPort: 7070
        env:
        - name: PORT
          value: "7070"
        - name: REDIS_ADDR
          value: "redis-cart:6379"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# cart-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: cart-service
  namespace: shopfast
spec:
  type: ClusterIP
  selector:
    app: cart-service
  ports:
  - port: 80
    targetPort: 7070
---
# redis-cart-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  namespace: shopfast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-cart
  template:
    metadata:
      labels:
        app: redis-cart
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
        - containerPort: 6379
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# redis-cart-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  namespace: shopfast
spec:
  type: ClusterIP
  selector:
    app: redis-cart
  ports:
  - port: 6379
    targetPort: 6379
---
# currency-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
  namespace: shopfast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
      - name: currency
        image: gcr.io/google-samples/microservices-demo/currencyservice:v0.8.0
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGING
          value: "1"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
# currency-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: currency-service
  namespace: shopfast
spec:
  type: ClusterIP
  selector:
    app: currency-service
  ports:
  - port: 80
    targetPort: 7000
---
# ad-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service
  namespace: shopfast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      containers:
      - name: ad
        image: gcr.io/google-samples/microservices-demo/adservice:v0.8.0
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_STATS
          value: "1"
        resources:
          requests:
            memory: "180Mi"
            cpu: "100m"
          limits:
            memory: "300Mi"
            cpu: "200m"
---
# ad-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ad-service
  namespace: shopfast
spec:
  type: ClusterIP
  selector:
    app: ad-service
  ports:
  - port: 80
    targetPort: 9555
---
# Updated Frontend with corrected services
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: shopfast
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: web-ui
        image: gcr.io/google-samples/microservices-demo/frontend:v0.8.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "product-catalog:80"
        - name: CHECKOUT_SERVICE_ADDR
          value: "auth-service:80"
        - name: RECOMMENDATION_SERVICE_ADDR
          value: "recommendation:80"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:80"
        - name: CART_SERVICE_ADDR
          value: "cart-service:80"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:80"
        - name: AD_SERVICE_ADDR
          value: "ad-service:80"
        - name: EMAIL_SERVICE_ADDR
          value: "email-service:80"
        - name: PAYMENT_SERVICE_ADDR
          value: "payment-service:80"
        - name: DISABLE_TRACING
          value: "1"
        - name: DISABLE_PROFILER
          value: "1"
        - name: DISABLE_DEBUGGER 
          value: "1"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"